# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('cif', models.CharField(max_length=20)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
